### ISSUE TITLE
1.14.4 - Crash while typing

### ISSUE THREAD

**Issue by RViper80** [CreeperHost/CreeperHostGui#167]
Someone had asked how to copy-paste the world seed from chat in-game.  I switched to the commands tab, typed /seed, and clicked on the seed to get it down into the chat line.  Selected that and cut it (ctrl-x).  Then when I switched back to the MT chat, and started typing, the game crashed with this error:

```
java.lang.ClassCastException: net.minecraft.client.gui.widget.TextFieldWidget cannot be cast to net.creeperhost.minetogether.client.gui.chat.GuiTextFieldLockable
	at net.creeperhost.minetogether.client.gui.chat.ingame.GuiChatOurs.charTyped(GuiChatOurs.java:116) ~[?:1.14.4-3.0.0-RC4] {re:classloading}
	at net.minecraft.client.KeyboardListener.lambda$onCharEvent$5(KeyboardListener.java:376) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches KeyboardListener Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:441) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.KeyboardListener.func_197963_a(KeyboardListener.java:374) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches KeyboardListener Transformer,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:39) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.platform.GLX.pollEvents(GLX.java:276) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:875) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,xf:fml:screenshotclipboard:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,xf:fml:screenshotclipboard:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) ~[1.14.4-forge-28.2.0.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.14.4-28.2.0.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}
```

[Full Crash Log](https://pastebin.com/WFDSjw2v)
[Full Forge Log](https://drive.google.com/open?id=11zGPaG8YDWrEZcZ7oRAqQeKiBu-GBBsq)

**Comment by gigabit101** [comment]
Fixed in RC5
