### ISSUE TITLE
Error occurred applying transform of coremod

### ISSUE THREAD

**Issue by Sunekaer** [CreeperHost/CreeperHostGui#196]
RC7
```
[00:36:51] [Server thread/ERROR]: Error occurred applying transform of coremod patches/ServerLoginNetHandler.js function MineTogether ServerLoginNetHandler Transformer
jdk.nashorn.internal.runtime.ECMAException: TypeError: Can not invoke method [jdk.internal.dynalink.beans.OverloadedDynamicMethod org.objectweb.asm.tree.InsnList.insert] with the passed arguments; they do not match any of its method signatures.
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkBean(NashornBottomLinker.java:98) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:71) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124) ~[nashorn.jar:?]
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:149) ~[nashorn.jar:?]
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:233) ~[nashorn.jar:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$52$998A$\^eval\_.patchTick(<eval>:50) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$51$288AAA$\^eval\_.patch(<eval>:12) ~[?:?]
	at jdk.nashorn.internal.scripts.Script$Recompilation$50$770A$\^eval\_.initializeCoreMod$transformer(<eval>:27) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:638) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:229) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:387) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:110) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18) ~[coremods-2.0.0-milestone.1.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10) ~[coremods-2.0.0-milestone.1.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) [coremods-2.0.0-milestone.1.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:168) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:112) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) [modlauncher-5.0.0-milestone.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:223) [?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by gigabit101** [comment]
Fixed in RC8 https://cdn.discordapp.com/attachments/670996283820867604/689804992671907953/minetogether-1.15.2-4.0.0-RC8.jar

**Comment by Sunekaer** [comment]
```
>....[MineTogether ServerLoginNetHandler Transformer]: Attempting to patch method: func_73660_a (func_73660_a)
[22:52:09] [Server thread/ERROR] [ne.mi.co.tr.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod patches/ServerLoginNetHandler.js function MineTogether ServerLoginNetHandler Transformer
jdk.nashorn.internal.runtime.ECMAException: TypeError: Can not invoke method [jdk.internal.dynalink.beans.OverloadedDynamicMethod
void org.objectweb.asm.tree.InsnList.insert(AbstractInsnNode,AbstractInsnNode)
void org.objectweb.asm.tree.InsnList.insert(AbstractInsnNode,InsnList)
void org.objectweb.asm.tree.InsnList.insert(AbstractInsnNode)
void org.objectweb.asm.tree.InsnList.insert(InsnList)
] with the passed arguments; they do not match any of its method signatures.
at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:?] {re:classloading}
at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213) ~[nashorn.jar:?] {re:classloading}
at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185) ~[nashorn.jar:?] {re:classloading}
at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172) ~[nashorn.jar:?] {re:classloading}
at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.linkBean(NashornBottomLinker.java:103) ~[nashorn.jar:?] {}
at jdk.nashorn.internal.runtime.linker.NashornBottomLinker.getGuardedInvocation(NashornBottomLinker.java:73) ~[nashorn.jar:?] {}
at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124) ~[nashorn.jar:?] {}
at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154) ~[nashorn.jar:?] {}
at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253) ~[nashorn.jar:?] {}
at jdk.nashorn.internal.scripts.Script$Recompilation$52$998A$\^eval\_.patchTick(<eval>:50) ~[?:?] {re:classloading}
at jdk.nashorn.internal.scripts.Script$Recompilation$51$288AAA$\^eval\_.patch(<eval>:12) ~[?:?] {re:classloading}
at jdk.nashorn.internal.scripts.Script$Recompilation$50$770A$\^eval\_.initializeCoreMod#transformer(<eval>:27) ~[?:?] {re:classloading}
at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639) ~[nashorn.jar:?] {}
at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?] {re:classloading}
at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?] {}
at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[nashorn.jar:?] {}
at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18) ~[coremods-2.0.0-milestone.1.jar:?] {}
at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10) ~[coremods-2.0.0-milestone.1.jar:?] {}
at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) [coremods-2.0.0-milestone.1.jar:?] {}
at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) [modlauncher-5.0.0-milestone.4.jar:?] {}
at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:168) [modlauncher-5.0.0-milestone.4.jar:?] {}
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:112) [modlauncher-5.0.0-milestone.4.jar:?] {}
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) [modlauncher-5.0.0-milestone.4.jar:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) [?:1.8.0_242] {}
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:223) [?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:329) [?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
```

**Comment by Sunekaer** [comment]
Still an issue

**Comment by gigabit101** [comment]
How?? I tested this on my server and it was fine... 😕

**Comment by gigabit101** [comment]
First time using the new ASM system so must have got something wrong somehow lol

**Comment by gigabit101** [comment]
Fixed in the latest build
