### ISSUE TITLE
Crash to desktop on openning chat

### ISSUE THREAD

**Issue by louisereay** [CreeperHost/CreeperHostGui#216]
[04Apr2020 14:04:34.915] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: ---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/4/20 2:04 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.client.gui.NewChatGui cannot be cast to net.creeperhost.minetogether.client.gui.chat.ingame.GuiNewChatOurs
	at net.creeperhost.minetogether.client.gui.chat.ingame.GuiChatOurs.init(GuiChatOurs.java:207) ~[?:1.15.2-4.0.0-Beta2] {re:classloading}
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:339) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:blur:hookBackgroundColor,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:801) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1513) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1376) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:905) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.30.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$461/2071522666.call(Unknown Source) [forge-1.15.2-31.1.30.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.creeperhost.minetogether.client.gui.chat.ingame.GuiChatOurs.init(GuiChatOurs.java:207)
	at net.minecraft.client.gui.screen.Screen.init(Screen.java:339)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:801)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1513)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Kittiaara'/53, l='MpServer', x=622.92, y=71.00, z=-134.70]]
	Chunk stats: Client Chunk Cache: 625, 361
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 5322851958993399611
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-112,72,80), Chunk: (at 0,4,0 in -7,5; contains blocks -112,0,80 to -97,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1725953 game time, 1926646 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:573)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$461/2071522666.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1169372256 bytes (1115 MB) / 3485990912 bytes (3324 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.30.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.30.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.30
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		pocketstorage-1.15.2-0.7.2.jar Pocket Storage Unit {pocketstorage@1.15.2-0.7.2 DONE}
		JAVD-1.0.0+build.9.minecraft.1.15.2.jar Just Another Void Dim {javd@1.0.0+build.9.minecraft.1.15.2 DONE}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		bambooeverything-1.15-1.0.0.jar Bamboo Everything {bambooeverything@1.15-1.0.0 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		rsgauges-1.15.2-1.2.2.jar Gauges and Switches {rsgauges@1.2.2 DONE}
		findme-1.15.2-1.2.1.jar Find Me {findme@NONE DONE}
		IronJetpacks-1.15.2-3.0.1.jar Iron Jetpacks {ironjetpacks@3.0.1 DONE}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 DONE}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		Powah-1.15.2-1.1.11.jar Powah {powah@1.1.11 DONE}
		ftb-gui-library-1.0.0.14.jar FTB GUI Library {ftbguilibrary@1.0.0.14 DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		potionofbees-1.15.2-1.0.0.jar Potion of Bees {potionofbees@1.15.2-1.0.0 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		Bookshelf-1.15.2-5.3.9.jar Bookshelf {bookshelf@5.3.9 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		buildinggadgets-3.3.4.jar Building Gadgets {buildinggadgets@3.3.4 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.9.17.409.jar Mekanism: Generators {mekanismgenerators@9.9.17 DONE}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 DONE}
		TOOLKIT-1.15.2-1.6.4.jar Tool Kit {toolkit@1.15.2-1.6.4 DONE}
		ftb-teams-1.0.0.5.jar FTB Teams {ftbteams@1.0.0.5 DONE}
		absentbydesign-1.15.2-1.0.5 .jar Absent By Design Mod {absentbydesign@1.15.2-1.0.5  DONE}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 DONE}
		quartz-chests-1.1.0.5.jar Quartz Chests {quartzchests@1.1.0.5 DONE}
		PackMenu-1.15.2-1.2.4.jar Pack Menu {packmenu@1.2.4 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		improved-stations-1.1.jar Improved Stations {improved-stations@1.1 DONE}
		entangled-1.2.1-mc1.15.jar Entangled {entangled@1.2 DONE}
		AmbientSounds_v3.0.19_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		mappy-1.15.2-1.0.6.jar Mappy {mappy@1.0.6 DONE}
		BiomesOPlenty-1.15.2-10.0.0.353-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.353 DONE}
		phosphor-mc1.15.2-forge-0.4.2-rc2.jar Phosphor {phosphor@0.4.2-rc2 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a DONE}
		Lollipop-1.15.2-1.0.13.jar Lollipop {lollipop@1.0.13 DONE}
		wtbw_lib-1.15.2-1.0.17.jar WTBW Library {wtbw_lib@1.0.17 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		simplybackpacks-1.15.2-1.4.5.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.5 DONE}
		portality-1.15.2-2.1.2-aaa257f.jar Portality {portality@2.1.2 DONE}
		curios-FORGE-1.15.2-2.0.2.1.jar Curios API {curios@FORGE-1.15.2-2.0.2.1 DONE}
		Patchouli-1.15.2-1.2-28.jar Patchouli {patchouli@1.15.2-1.2-28 DONE}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 DONE}
		tanknull-1.8a.jar Tank Null {tanknull@1.8a DONE}
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		ftb-ultimine-1.0.8.3.jar FTB Ultimine {ftbultimine@1.0.8.3 DONE}
		NaturesAura-23.4.jar Nature's Aura {naturesaura@version DONE}
		MekanismTools-1.15.2-9.9.17.409.jar Mekanism: Tools {mekanismtools@9.9.17 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		cc-tweaked-1.15.2-1.86.2.jar CC: Tweaked {computercraft@1.86.2 DONE}
		mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 DONE}
		the_bumblezone-1.15.2-1.0.4.jar The Bumblezone {the_bumblezone@1.15.2-1.0.4 DONE}
		YAMDA-5.0.2.jar YAMDA {yamda@5.0.2 DONE}
		speedyladders-1.15.2-1.jar Speedy Ladders {speedyladders@1.15.2-1 DONE}
		Disenchanting_(forge)_1.15.2-1.2.0.jar Disenchanting {disenchanting@1.2.0 DONE}
		GameMenuModOption-1.15.2-1.2.jar GameMenuModOption {gamemenumodoption@1.2 DONE}
		SimpleDiscordRichPresence-1.15.2-1.2.6.jar Simple Discord Rich Presence {sdrp@1.15.2-1.2.6 DONE}
		QuantumStorage-1.15.2-5.1.1.jar QuantumStorage {quantumstorage@NONE DONE}
		Cyclic-1.15.2-0.2.0.jar Cyclic {cyclic@1.15.2-0.2.0 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		jmh_1.15.2-2.2.jar Just Mob Heads {jmh@2.2 DONE}
		Cucumber-1.15.2-3.0.3.jar Cucumber Library {cucumber@3.0.3 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		snad-1.8.4.22a-1.15.2.jar Snad {snad@1.8.3.3a DONE}
		item-filters-2.2.0.14.jar Item Filters {itemfilters@2.2.0.14 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		kubejs-2.6.0.28.jar KubeJS {kubejs@2.6.0.28 DONE}
		longfallboots-1.4.0b.jar Long Fall Boots {longfallboots@1.4.0b DONE}
		lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar Lithium {lithium@0.4.6-rc3 DONE}
		goblintraders-1.2.0-1.15.2.jar Goblin Traders {goblintraders@1.2.0 DONE}
		Mekanism-1.15.2-9.9.17.409.jar Mekanism {mekanism@9.9.17 DONE}
		polarizingbiomes-1.15.1-v1.0.jar Polarizing Biomes {polarizingbiomes@v1.0 DONE}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		LightOverlay-4.3.jar Light Overlay Forge {lightoverlay-forge@4.3 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		good-nights-sleep-1.15.2-1.0.3.jar Good Night's Sleep {goodnightsleep@1.0.3 DONE}
		additionalbars-1.2.3.jar Additional Bars {additionalbars@1.2.3 DONE}
		SimpleStorageNetwork-1.15.2-0.3.2.jar Simple Storage Network {storagenetwork@1.15.2-0.3.2 DONE}
		DimStorage-1.15.2-3.0.3.jar DimStorage {dimstorage@3.0.3 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		BotanyPots-1.15.2-2.0.5.jar BotanyPots {botanypots@2.0.5 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		RingOfTeleport-1.15.2-1.1.19.jar Ring of Teleport {ring_of_teleport@1.1.19 DONE}
		snowundertrees-1.15.1-v1.0.jar Snow Under Trees {snowundertrees@v1.0 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		mcjtylib-1.15-4.0.3-alpha.jar McJtyLib {mcjtylib@1.15-4.0.3-alpha DONE}
		rftoolsbase-1.15-1.0.1-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.1-alpha DONE}
		xnet-1.15-2.0.2-alpha.jar XNet {xnet@1.15-2.0.2-alpha DONE}
		rftoolsstorage-1.15-1.0.3-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.3-alpha DONE}
		travellersboots-1.15.2-1.3.2.jar Traveller's Boots {travellersboots@1.3.1 DONE}
		PackingTape-1.15.2-0.9.5.jar Packing Tape {packingtape@0.9.5 DONE}
		mininggadgets-1.3.5.jar Mining Gadgets {mininggadgets@1.3.5 DONE}
		entitydetectors-1.5.2-1.0.0.jar Entity Detectors {entitydetectors@1.5.2-1.0.0 DONE}
		endercompass-2.0.jar Ender Compass {endercompass@2.0 DONE}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha DONE}
		ftb-chunks-1.0.1.5.jar FTB Chunks {ftbchunks@1.0.1.5 DONE}
		campfiretorches-1.15.2-1.0.2.jar Campfire Torches {campfiretorches@1.15.2-1.0.2 DONE}
		forge-1.15.2-31.1.30-universal.jar Forge {forge@31.1.30 DONE}
		wtbw_core-1.15.2-1.0.16.jar WTBW Core {wtbw_core@1.0.16 DONE}
		wtbw_tools-1.15.2-1.0.19.jar WTBW Tools {wtbw_tools@1.0.19 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 DONE}
		forge-1.15.2-31.1.30-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.3.2b.jar CoFH Core {cofh_core@0.3.2b DONE}
		ensorcellation-1.15.2-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b DONE}
		rftoolsutility-1.15-2.0.1-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.1-alpha DONE}
		theoneprobe-1.15-2.0.2.jar The One Probe {theoneprobe@1.15-2.0.2 DONE}
		distance-1.0.0.1.jar Distance {distance@1.0.0.1 DONE}
		clockout-1.15.2-1.0.0.jar Clockout {clockout@1.15.2-1.0.0 DONE}
		playerplates-1.15-forge-1.0.0.jar Player Plates {playerplates@1.15-forge-1.0.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.15.2-2.3.7.jar Titanium {titanium@2.3.7 DONE}
		moolands-1.15.2-1.2.0.jar Moolands {moolands@1.2.0 DONE}
		useful_railroads-1.15.2-1.3.2.21.jar Useful Railroads {usefulrailroads@1.3.2.21 DONE}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 DONE}
		wtbw_machines-1.15.2-1.0.19.jar WTBW Machines {wtbw_machines@1.0.19 DONE}
		concreteconversion-1.15.2-4.0.0.0.jar Concrete Conversion {concreteconversion@1.15.2-4.0.0.0 DONE}
		archers_paradox-1.15.2-0.3.0b.jar Archer's Paradox {archers_paradox@0.3.0b DONE}
		SoulShardsRespawn-forge-1.15.2-1.2.0-15.jar Soul Shards Respawn {soulshards@version DONE}
		Ding-1.15.2-1.1.0.jar Ding {ding@1.1.0 DONE}
		rftoolsbuilder-1.15-2.0.1-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.1-alpha DONE}
		MiscAdditions-1.2.3.jar Misc Additions {miscadditions@1.2.3 DONE}
		HunterMod-1.15.2-1.0.3.jar Hunter Mod {huntermod@1.0.3 DONE}
		wtbw_decoration-1.15.2-1.0.14.jar WTBW Decoration {wtbw_decoration@1.0.14 DONE}
		gravestone-1.17.3.jar Gravestone Mod {gravestone@1.17.3 DONE}
		ftb-backups-2.1.0.1.jar FTB Utilities: Backups {ftbbackups@2.1.0.1 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		performant-1.15-1.11.jar Performant {performant@1.11 DONE}
		DoubleSlabs-1.15-2.0.3.jar Double Slabs {doubleslabs@2.0.3 DONE}
		harvest-1.15.2-1.0.1.jar Harvest {harvest@1.0.1 DONE}
		jph_1.15.2-1.0.jar Just Player Heads {jph@1.0 DONE}
		tubesreloaded-1.15.2-1.3.0c.jar Tubes Reloaded {tubesreloaded@1.15.2-1.3.0c DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		Transport-1.15.2-2.2.0.jar Transport {transport@1.15.2-2.2.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		engineersdecor-1.15.2-1.0.20-b3.jar Engineer's Decor {engineersdecor@1.0.20-b3 DONE}
		minetogether-1.15.2-4.0.0-Beta2.jar MineTogether {minetogether@1.15.2-4.0.0-Beta2 DONE}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 DONE}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 DONE}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		waterworks-1.15.2-2.1.1.jar Waterworks {waterworks@1.15.2-2.1.1 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		extremeSoundMuffler-beta-1.15.2-1.1.jar Extreme Sound Muffler {extremesoundmuffler@beta-1.15.2-1.1 DONE}
		draw_bridge-1.15.2-1.4.3.18.jar Draw Bridge {drawbridge@1.4.3.18 DONE}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 DONE}
	Launched Version: 1.15.2-forge-31.1.30
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 450.12, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, kubejs:resource_pack (incompatible), packmenu
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
[04Apr2020 14:04:34.929] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:103]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Louise\AppData\Roaming\FTBA\instances\ec35fa3f-2d36-4fb3-817d-2ec0f1a5397b\crash-reports\crash-2020-04-04_14.04.34-client.txt
[04Apr2020 14:04:34.930] [DiscordRP Stop/DEBUG] [IPCClient/]: Closing IPC Pipe...
[04Apr2020 14:04:34.931] [DiscordRP Stop/DEBUG] [IPCClient/]: Sent packet: Pkt:CLOSE{"nonce":"8254bd46-91de-43c2-b0ec-5eb1af88d841"}
[04Apr2020 14:04:34.930] [Discord Rich Presence Stop Thread/INFO] [UTeamCore/]: Discord client closed.
[04Apr2020 14:04:34.931] [DiscordRP Stop/INFO] [Simple Discord Rich Presence/]: Discord client closed.

**Comment by AKTheKnight** [comment]
https://pste.ch/gapatigovi.md

**Comment by AKTheKnight** [comment]
Still happening on Beta 3_1

https://pste.ch/ojuhelalen.rb

**Comment by gigabit101** [comment]
Fixed in beta4
