### ISSUE TITLE
Overwhelming console spam

### ISSUE THREAD

**Issue by aaronhowser1** [CreeperHost/CreeperHostGui#259]
This is using `minetogether-1.10.2-2.2.4`

Excerpt [here](https://pastebin.com/RGCjDLf4), whole files here:

[latest.log](https://github.com/CreeperHost/CreeperHostGui/files/4671688/latest.log)
[debug.log](https://github.com/CreeperHost/CreeperHostGui/files/4671689/debug.log)

**Comment by Draylynn** [comment]
Does this happen on build 2.2.5?
2.2.5: https://tinyurl.com/ya7bych3

**Comment by aaronhowser1** [comment]
Nope! No spam whatsoever.

**Comment by aaronhowser1** [comment]
Actually I am getting:
```
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_212]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_212]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_212]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_212]
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_212]
	at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) ~[?:1.8.0_212]
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933) ~[?:1.8.0_212]
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[?:1.8.0_212]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_212]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_212]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_212]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) ~[?:1.8.0_212]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482) ~[?:1.8.0_212]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782) ~[?:1.8.0_212]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481) ~[?:1.8.0_212]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_212]
	at net.creeperhost.minetogether.common.WebUtils.methodWebResponse(WebUtils.java:132) ~[WebUtils.class:?]
	at net.creeperhost.minetogether.common.WebUtils.putWebResponse(WebUtils.java:170) ~[WebUtils.class:?]
	at net.creeperhost.minetogether.paul.Callbacks.getInvite(Callbacks.java:293) ~[Callbacks.class:?]
	at net.creeperhost.minetogether.EventHandler.lambda$onClientTick$3(EventHandler.java:735) ~[EventHandler.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
and
```
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: java.net.SocketTimeoutException: connect timed out
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.net.Socket.connect(Socket.java:589)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1040)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1038)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.security.AccessController.doPrivileged(Native Method)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1037)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.http.HttpURLConnection.access$100(HttpURLConnection.java:91)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1301)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.http.HttpURLConnection$8.run(HttpURLConnection.java:1299)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.security.AccessController.doPrivileged(Native Method)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1298)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at net.creeperhost.minetogether.common.WebUtils.methodWebResponse(WebUtils.java:121)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at net.creeperhost.minetogether.common.WebUtils.putWebResponse(WebUtils.java:170)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at net.creeperhost.minetogether.paul.Callbacks.getInvite(Callbacks.java:293)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at net.creeperhost.minetogether.EventHandler.lambda$onClientTick$3(EventHandler.java:735)
[14:23:59] [MineTogether invite check thread/INFO] [STDERR]: [net.creeperhost.minetogether.common.WebUtils:methodWebResponse:128]: 	at java.lang.Thread.run(Thread.java:748)
```

but those are the only instances in the console. A big improvement over what it was.

**Comment by gigabit101** [comment]
The errors are normal as they are errors, I have however toned down the spam, I am interested in why this is failing to get the data from our API. Have you changed any of the mods configs?

**Comment by ThePaul-T** [comment]
Closing due to lack of updates.
