### ISSUE TITLE
crash when opening chat

### ISSUE THREAD

**Issue by Velocihater** [CreeperHost/CreeperHostGui#35]
---- Minecraft Crash Report ----
// I blame K4Unl, author of MineTogether.

Time: 2018-10-15 18:20:31 CDT
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.client.gui.GuiNewChat cannot be cast to net.creeperhost.minetogether.gui.chat.ingame.GuiNewChatOurs
    at net.creeperhost.minetogether.gui.chat.ingame.GuiChatOurs.initGui(GuiChatOurs.java:138)
    at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:478)
    at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:1017)
    at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2210)
    at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2019)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1807)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1097)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Velocihater** [comment]
https://pastebin.com/y3beTVDY

**Comment by Cloudhunter** [comment]
I can't think of a code path which would cause this, but obviously there is.

Can you provide your minetogether.cfg please?

**Comment by gigabit101** [comment]
This should be fixed but will need testing

**Comment by RonaldvanMeer** [comment]
I have the exact same problem -> when opening chat window (pressing T while in game on a server) the minecraft client crashes.
I'd like to test your solution. I'm looking for your fixed version so i can place this inside my mods directory

**Comment by RonaldvanMeer** [comment]
mintogheter.cfg -> after deletion of original cfg file (system regenerates):
{
  "curseProjectID": "Insert curse project ID here",
  "promoCode": "Insert Promo Code here",
  "creeperhostEnabled": true,
  "mpMenuEnabled": true,
  "mainMenuEnabled": true,
  "serverHostButtonImage": true,
  "serverHostMenuImage": true,
  "sivIntegration": true,
  "serverListEnabled": true,
  "chatEnabled": true,
  "pregenDiameter": 120
}

**Comment by gigabit101** [comment]
This was fixed in the last release
