### ISSUE TITLE
crashes on start up

### ISSUE THREAD

**Issue by lex3274** [CreeperHost/CreeperHostGui#362]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'minecraft 1.16.3'
2. Click on 'start'
3. Scroll down to 'just wait ig for minecraft to load'

**Expected behaviour**
error happens

**Screenshots**
![image](https://user-images.githubusercontent.com/72877887/96010317-85a17900-0df6-11eb-85a7-9f9bc1365c76.png)
![image](https://user-images.githubusercontent.com/72877887/96010457-a79afb80-0df6-11eb-8eee-9c7932de2cfa.png)
(don't know if that would be helpful but yea
**Versions**
Please give all the versions you are using:

Minecraft:1.16.3

Forge:34.1.19

MineTogether:1.16.2 (idk if that's a typo on curseforge or not but) -4.1.1

**Additional context**

**Comment by gigabit101** [comment]
Can you please post the full log?

**Comment by gigabit101** [comment]
Closing due to inactivity, Feel free to reopen if the issue continues

**Comment by lex3274** [comment]
sorry i did not see this for some strange reason, sorry yea. here
txt form:
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/22/20 9:26 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$4203/1507906849.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3737/181022659.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.19.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$434/1019009267.call(Unknown Source) [forge-1.16.3-34.1.19.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.creeperhost.minetogether.MineTogether.findOurJar(MineTogether.java:289) ~[?:1.16.2-4.1.1] {re:classloading}
-- MOD minetogether --
Details:
	Mod File: MineTogether-1.16.2-4.1.1.jar
	Failure message: MineTogether (minetogether) encountered an error during the sided_setup event phase
		java.lang.NullPointerException: null
	Mod Version: 1.16.2-4.1.1
	Mod Issue URL: https://github.com/CreeperHost/MineTogether/issues
	Exception message: java.lang.NullPointerException
Stacktrace:
	at net.creeperhost.minetogether.MineTogether.findOurJar(MineTogether.java:289) ~[?:1.16.2-4.1.1] {re:classloading}
	at net.creeperhost.minetogether.MineTogether.preInitClient(MineTogether.java:165) ~[?:1.16.2-4.1.1] {re:classloading}
	at net.creeperhost.minetogether.MineTogether$$Lambda$3254/328606644.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2910/1025786379.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:34.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3095/751460639.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4558359944 bytes (4347 MB) / 5100273664 bytes (4864 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.19.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.19.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.19.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.19.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G4_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.19.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.19
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.19-client.jar Minecraft {minecraft@1.16.3 ENQUEUE_IMC}
		ClientTweaks_1.16.3-5.2.0.jar Client Tweaks {clienttweaks@5.2.0 ENQUEUE_IMC}
		theoneprobe-1.16-3.0.4-beta.jar The One Probe {theoneprobe@1.16-3.0.4-beta ENQUEUE_IMC}
		AmbientSounds_v3.0.21_mc1.16.2.jar Ambient Sounds {ambientsounds@3.0.3 ENQUEUE_IMC}
		MouseTweaks-2.13-mc1.16.2.jar Mouse Tweaks {mousetweaks@2.13 ENQUEUE_IMC}
		ToolSwap-1.16.2-1.2.0.jar ToolSwap {toolswap@1.2.0 ENQUEUE_IMC}
		justenoughbeacons-3.0-1.16.1.jar Just Enough Beacons {justenoughbeacons@3.0-1.16.1 ENQUEUE_IMC}
		blood-particles-1.16.3-1.0.1.jar Blood Particles {blood_particles@1.0.1 ENQUEUE_IMC}
		CreativeCore_v2.0.7_mc1.16.2.jar CreativeCore {creativecore@2.0.0 ENQUEUE_IMC}
		beenfo-1.16.3-forge34.0.1-1.2.jar Beenfo {beenfo@1.16.3-forge34.0.1-1.2 ENQUEUE_IMC}
		MinecraftCapes+Forge+1.16.2-v10.jar MinecraftCapes Mod {minecraftcapes@v10 ENQUEUE_IMC}
		jei-1.16.2-7.3.2.28.jar Just Enough Items {jei@7.3.2.28 ENQUEUE_IMC}
		OptiForge-MC1.16.3-0.3.4.jar OptiForge {optiforge@0.3.4 ENQUEUE_IMC}
		Ding-1.16.3-1.2.0.jar Ding {ding@1.2.0 ENQUEUE_IMC}
		ToroCrafts-Damage-Indicators-Mod-1.16.3.jar ToroHealth {torohealth@NONE ENQUEUE_IMC}
		jeiintegration_1.16.3-6.0.0.8.jar JEI Integration {jeiintegration@6.0.0.8 ENQUEUE_IMC}
		collective-1.16.3-1.51.jar Collective {collective@1.51 ENQUEUE_IMC}
		BetterTitleScreen-1.16.2-1.10.1.jar Better Title Screen {bettertitlescreen@1.16.2-1.10.1 ENQUEUE_IMC}
		light-overlay-5.5.2.jar Light Overlay Forge {lightoverlay-forge@NONE ENQUEUE_IMC}
		EnhancedVisuals_v1.3.18_mc1.16.2.jar EnhancedVisuals {enhancedvisuals@1.3.0 ENQUEUE_IMC}
		Placebo-1.16.3-4.3.2.jar Placebo {placebo@4.3.2 ENQUEUE_IMC}
		u_team_core-1.16.3-3.1.9.181.jar U Team Core {uteamcore@3.1.9.181 ENQUEUE_IMC}
		FastFurnace-1.16.3-4.3.0.jar FastFurnace {fastfurnace@4.3.0 ENQUEUE_IMC}
		MineTogether-1.16.2-4.1.1.jar MineTogether {minetogether@1.16.2-4.1.1 ERROR}
		JEITweaker-1.16.3-1.0.1.4.jar JEI Tweaker {jeitweaker@1.0.1.4 ENQUEUE_IMC}
		cloth-config-forge-4.1.0.jar Cloth Config v4 API {cloth-config@4.0 ENQUEUE_IMC}
		FpsReducer-mc1.16.3-1.18.jar FPS Reducer {fpsreducer@mc1.16.3-1.18 ENQUEUE_IMC}
		JustEnoughResources-1.16.3-0.12.0.100.jar Just Enough Resources {jeresources@0.12.0.100 ENQUEUE_IMC}
		forgemod_VoxelMap-1.10.11_for_1.16.2.jar VoxelMap {voxelmap@1.10.10 ENQUEUE_IMC}
		forge-1.16.3-34.1.19-universal.jar Forge {forge@34.1.19 ENQUEUE_IMC}
		AppleSkin-mc1.16.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 ENQUEUE_IMC}
		SoundFilters-0.14_for_1.16.2.jar Sound Filters {soundfilters@0.14_for_1.16.2 ENQUEUE_IMC}
		ServerTabInfo-1.16.3-1.3.3.jar Server Tab Info {servertabinfo@1.3.3 ENQUEUE_IMC}
		hidehands_1.16.3_1.1.jar Hide Hands {hidehands@1.1 ENQUEUE_IMC}
		BetterAdvancements-1.16.3-0.1.0.102.jar Better Advancements {betteradvancements@0.1.0.102 ENQUEUE_IMC}
	Crash Report UUID: 48265bd3-cccc-47bf-a887-11e6ec80c893
	OptiFine Version: OptiFine_1.16.3_HD_U_G4_pre2
	OptiFine Build: 20201007-190609
	Render Distance Chunks: 27
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7324
	OpenGlRenderer: Intel(R) UHD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 8
