### ISSUE TITLE
Crash on accepting invite

### ISSUE THREAD

**Issue by CH-Paul-T** [CreeperHost/CreeperHostGui#47]
When invited by friend it crashes you.

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.ServerListEntryNormal.func_192634_a(ServerListEntryNormal.java:165)
	at net.creeperhost.minetogether.gui.hacky.ServerListEntryWrapperNew.draw(ServerListEntryWrapperNew.java:11)
	at net.creeperhost.minetogether.gui.serverlist.gui.elements.ServerListEntryPublic.ourDrawEntry(ServerListEntryPublic.java:55)
	at net.creeperhost.minetogether.gui.serverlist.gui.GuiInvited.func_73863_a(GuiInvited.java:97)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by gigabit101** [comment]
This was fixed in the last release
