### ISSUE TITLE
[Bug]: bufferedWriter is null on quit

### ISSUE THREAD

**Issue by manmaed** [CreeperHost/CreeperHostGui#598]
### Describe the bug

bufferedWriter is null

### Steps to reproduce

close game

### Expected behaviour

not to do whatt it dose

### Version

5.2.3

### Minecraft Version

1.18.2

### ModLoader Version

Forge 40.1.16

### Additional Information

[17:21:40] [Thread-12/INFO] [ne.cr.mi.MineTogetherCommon/]: Shutdown called, Stopping our threads
java.lang.NullPointerException: Cannot invoke "java.io.BufferedWriter.write(char[])" because "net.creeperhost.minetogether.lib.chat.irc.IrcHandler.bufferedWriter" is null
	at TRANSFORMER/minetogether@5.2.3/net.creeperhost.minetogether.lib.chat.irc.IrcHandler.sendString(IrcHandler.java:210)
	at TRANSFORMER/minetogether@5.2.3/net.creeperhost.minetogether.MineTogetherClient.lambda$init$0(MineTogetherClient.java:55)
	at java.base/java.lang.Thread.run(Thread.java:833)
[17:21:40] [DiscordRP Stop/INFO] [co.su.mo.sd.di.DiscordRichPresence/]: Discord client closed.
[17:21:40] [Thread-12/INFO] [ne.cr.mi.li.ch.ir.IrcHandler/]: Stopping IRC Socket
[17:21:40] [Thread-12/ERROR] [ne.cr.mi.li.ch.ir.IrcHandler/]: Socket is already null
[17:21:40] [Thread-12/INFO] [ne.cr.mi.li.ch.ir.IrcHandler/]: Force quitting chat thread

**Comment by gigabit101** [comment]
Should be fixed in latest version
