### ISSUE TITLE
[Bug]: PircBotX errors in the client log (loading phase)

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/CreeperHostGui#626]
### Describe the bug

There are multiple errors in what happens to be the loading phase of the mod, with the "PircBotX".

### Steps to reproduce

1. Load the modpack StoneBlock 3 1.0.1
2. Check your log go as the game loads

### Expected behaviour

Not sure... These are labeled as "ERROR" so I'm guessing it's not intended

### Screenshots

Part of log, obfuscated some parts since I have no clue if some info is private in there. I have the full log, contact me through internal channels if you need it:
```
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekDissolution, with priority 0
[06:47:11] [Immersive Engineering Contributors Thread/INFO] [immersiveengineering/]: Attempting to download special revolvers from GitHub
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekFluidSlurryToSlurry, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekMetallurgicInfuser, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekItemStackGasToItemStack, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekChemicalCrystallizer, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekPressurizedReaction, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekItemStackToPigment, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekSawmill, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekItemStackToItemStack, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekFluidToFluid, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekPaintingMachine, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded RecipeType Mapper: MekPigmentMixer, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded NBT Processor: EnchantmentProcessor, with priority 0
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded NBT Processor: DamageProcessor, with priority 2147483647
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded NBT Processor: StoredEMCProcessor, with priority 0
[06:47:11] [Worker-Main-37/INFO] [co.da.se.ServerConfigUpdater/]: Attempting to delete 1 files/folders defined in config
[06:47:11] [Worker-Main-42/INFO] [projecte/]: Found and loaded NBT Processor: MekanismContentsProcessor, with priority 0
[06:47:11] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: Global Forge version check system disabled, no further processing.
[06:47:11] [Worker-Main-32/INFO] [incontrol/]: Reading rules from spawn.json
[06:47:11] [Worker-Main-30/INFO] [Mekanism/]: Loaded 'Mekanism Generators' module.
[06:47:11] [Worker-Main-41/INFO] [Mekanism/]: Loaded 'Mekanism: Tools' module.
[06:47:11] [Worker-Main-46/INFO] [Mekanism/]: Fake player readout: UUID = 46e82cd0-d480-3d48-800a-77431ede078e, name = [Mekanism]
[06:47:11] [Worker-Main-46/INFO] [Mekanism/]: Mod loaded.
[06:47:11] [Worker-Main-41/INFO] [travel_anchors/]: Loading TravelAnchors
[06:47:11] [Worker-Main-37/INFO] [mcjtylib/]: RFTools Storage Detected XNet: enabling support
[06:47:11] [MineTogether IRC Client/ERROR] [ne.cr.mi.re.or.pi.PircBotX/]: Exception encountered when parsing line :R3GEN!server.ip.net MODE #superspecialdevclub +v MTXXXXX
net.creeperhost.minetogether.repack.org.pircbotx.exception.DaoException: UNKNOWN_CHANNEL: #superspecialdevclub 
	at net.creeperhost.minetogether.repack.org.pircbotx.UserChannelDao.getChannel(UserChannelDao.java:447) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.InputParser.processMode(InputParser.java:1067) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.InputParser.processCommand(InputParser.java:677) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.InputParser.handleLine(InputParser.java:419) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.PircBotX.processNextLine(PircBotX.java:427) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:374) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.PircBotX.connect(PircBotX.java:362) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.PircBotX.startBot(PircBotX.java:199) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.lib.chat.irc.pircbotx.PircBotClient.lambda$startClient$0(PircBotClient.java:88) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at java.lang.Thread.run(Unknown Source) [?:?] {}

[06:50:31] [MineTogether IRC Client/ERROR] [ne.cr.mi.re.or.pi.PircBotX/]: Exception encountered when parsing line :MXXXXX!MineTogeth@HEX.HEX.HEX.IP QUIT :Quit: 
java.lang.NullPointerException: Issue #274: No user snapshot for User(super=UserHostmask(extbanPrefix=null, nick=MTXXXXX, login=MineTogeth, hostname=HEX.HEX.HEX.IP), userId=UUID, realName={"p":"string","b":"base64"}, awayMessage=null, ircop=false, server=abcd.minetogether.io, hops=0)
	at net.creeperhost.minetogether.repack.org.pircbotx.UserChannelMap.createSnapshot(UserChannelMap.java:163) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.UserChannelDao.createSnapshot(UserChannelDao.java:618) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.InputParser.processCommand(InputParser.java:642) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.InputParser.handleLine(InputParser.java:419) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.PircBotX.processNextLine(PircBotX.java:427) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:374) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.PircBotX.connect(PircBotX.java:362) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.repack.org.pircbotx.PircBotX.startBot(PircBotX.java:199) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.creeperhost.minetogether.lib.chat.irc.pircbotx.PircBotClient.lambda$startClient$0(PircBotClient.java:88) ~[minetogether-forge-1.18.2-6.0.7.jar%23187!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at java.lang.Thread.run(Unknown Source) [?:?] {}
```

### Version

minetogether-forge-1.18.2-6.0.7.jar

### Minecraft Version

1.18.2

### ModLoader Version

Forge 40.1.84

### Additional Information

This is happening in the FTB StoneBlock 3 modpack, version 1.0.1.

Thanks in advance!

**Comment by covers1624** [comment]
Can you please attempt to reproduce this issue with verbose logging enabled in the config?

This issue seems to be caused by the IRC Library not receiving the `JOIN` irc event.

**Comment by Raidobw2** [comment]
Sure thing, give me a few minutes to try that out

**Comment by Raidobw2** [comment]
I've poked you in internal channels, poke me back there if you need more info, that might be easier for that issue

**Comment by gigabit101** [comment]
closed due to inactivity
