### ISSUE TITLE
[Bug]: Exception in log when hovering non image link

### ISSUE THREAD

**Issue by Raidobw2** [CreeperHost/CreeperHostGui#628]
### Describe the bug

Not sure, covers knows what this is about!

### Steps to reproduce

Hover a link in the MT chat (such as the Discord) then you will see in the log:

```
[03Nov2022 05:55:28.916] [preview-render-0/ERROR] [net.creeperhost.minetogether.polylib.gui.PreviewRenderer/]: Failed to load preview for: https://discord.gg/J4hYB6M
java.io.IOException: Could not load image: Image not of any known type, or corrupt
	at com.mojang.blaze3d.platform.NativeImage.m_85051_(NativeImage.java:134) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at com.mojang.blaze3d.platform.NativeImage.m_85048_(NativeImage.java:108) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at com.mojang.blaze3d.platform.NativeImage.m_85058_(NativeImage.java:99) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at net.creeperhost.minetogether.polylib.gui.PreviewRenderer.load(PreviewRenderer.java:100) ~[minetogether-forge-1.18.2-6.0.8.jar%23187!/:?]
	at net.creeperhost.minetogether.polylib.gui.PreviewRenderer.lambda$compute$1(PreviewRenderer.java:93) ~[minetogether-forge-1.18.2-6.0.8.jar%23187!/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

### Expected behaviour

To not throw an error

### Screenshots

![image](https://user-images.githubusercontent.com/17010632/199696094-c8c94d5d-bdb3-470a-ab4f-3f2f49bdb16e.png)

### Version

minetogether-forge-1.18.2-6.0.8.jar

### Minecraft Version

1.18.2

### ModLoader Version

Forge 40.1.84

### Additional Information

Thanks!

**Comment by covers1624** [comment]
This is now resolved in MineTogether 6.0.9.
