### ISSUE TITLE
[Bug]: Text wrapping the wrong way.

### ISSUE THREAD

**Issue by covers1624** [CreeperHost/CreeperHostGui#643]
### Describe the bug

Text wraps the wrong way in either the Chat Screen or In-Game.

### Steps to reproduce

Wrap a chat message.

### Expected behaviour

Not break.

### Version

6.0.9

### Minecraft Version

1.18.2

### ModLoader Version

Any

**Comment by covers1624** [comment]
Having a real hard time reproducing this issue..

Can occasionally result in this crash:
```
[06Nov2022 10:58:34.676] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:903) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1046) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.IndexOutOfBoundsException: Index 575 out of bounds for length 575
	at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
	at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
	at java.util.ArrayList.get(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.components.AbstractSelectionList$TrackedList.get(AbstractSelectionList.java:566) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at net.minecraft.client.gui.components.AbstractSelectionList$TrackedList.get(AbstractSelectionList.java:561) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.m_93500_(AbstractSelectionList.java:118) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.m_93451_(AbstractSelectionList.java:440) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6305_(AbstractSelectionList.java:201) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at net.creeperhost.minetogether.chat.gui.ChatScrollList.m_6305_(ChatScrollList.java:104) ~[minetogether-forge-1.18.2-6.0.9.jar%23187!/:?]
	at net.minecraft.client.gui.screens.Screen.m_6305_(Screen.java:104) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	at net.creeperhost.minetogether.chat.gui.ChatScreen.m_6305_(ChatScreen.java:190) ~[minetogether-forge-1.18.2-6.0.9.jar%23187!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:403) ~[forge-1.18.2-40.1.84-universal.jar%23268!/:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) ~[forge-1.18.2-40.1.84-universal.jar%23268!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:890) ~[client-1.18.2-20220404.173914-srg.jar%23263!/:?]
	... 16 more
```

**Comment by gigabit101** [comment]
closed due to inactivity
