### ISSUE TITLE
[Bug]: IRC event listener gets killed incorrectly.

### ISSUE THREAD

**Issue by covers1624** [CreeperHost/CreeperHostGui#648]
### Describe the bug

AAA

### Steps to reproduce

AAA

### Expected behaviour

AAA

### Version

6.0.9

### Minecraft Version

1.18.2

### ModLoader Version

any

### Additional Information

```
[01:17:30] [MineTogether IRC Client/ERROR]: Exception encountered during connect
java.util.concurrent.RejectedExecutionException: Task net.creeperhost.minetogether.repack.org.pircbotx.hooks.managers.AbstractListenerManager$ExecuteListenerRunnable@4670f9b0 rejected from java.util.concurrent.ThreadPoolExecutor@46d62229[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 16]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source) ~[?:?]
	at net.creeperhost.minetogether.repack.org.pircbotx.hooks.managers.SequentialListenerManager$PooledListenerExecutor.handleEvent(SequentialListenerManager.java:230) ~[minetogether-forge-1.18.2-6.0.9.jar%2391!/:?]
	at net.creeperhost.minetogether.repack.org.pircbotx.hooks.managers.SequentialListenerManager.onEvent(SequentialListenerManager.java:93) ~[minetogether-forge-1.18.2-6.0.9.jar%2391!/:?]
	at net.creeperhost.minetogether.repack.org.pircbotx.Utils.dispatchEvent(Utils.java:49) ~[minetogether-forge-1.18.2-6.0.9.jar%2391!/:?]
	at net.creeperhost.minetogether.repack.org.pircbotx.PircBotX.startBot(PircBotX.java:198) ~[minetogether-forge-1.18.2-6.0.9.jar%2391!/:?]
	at net.creeperhost.minetogether.lib.chat.irc.pircbotx.PircBotClient.lambda$startClient$0(PircBotClient.java:89) ~[minetogether-forge-1.18.2-6.0.9.jar%2391!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by gigabit101** [comment]
closed due to inactivity
