### ISSUE TITLE
[Bug]: Errors "Failed to do update."

### ISSUE THREAD

**Issue by cinek159** [CreeperHost/CreeperHostGui#685]
### Describe the bug

Spamming console "Failed to do update. (...)

[MineTogether Server List Thread/ERROR] [net.creeperhost.minetogether.server.ServerListThread]: Failed to do update.
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at net.creeperhost.minetogether.lib.web.ApiResponse.getStatus(ApiResponse.java:18) ~[minetogether-forge-1.18.2-6.0.13.jar%23175!/:?]
	at net.creeperhost.minetogether.server.ServerListThread.run(ServerListThread.java:53) [minetogether-forge-1.18.2-6.0.13.jar%23175!/:?]

### Steps to reproduce

Open console

### Expected behaviour

Its only an error, or its a problem with update server list?

### Version

minetogether-forge-1.18.2-6.0.13

### Minecraft Version

1.18.2

### ModLoader Version

Forge

### Additional Information

Ftb stoneblock 3
[latest.log](https://pastebin.com/YaRTzgYD)
[debug.log](https://pastebin.com/60WAC9b7)

**Comment by cinek159** [comment]
.

**Comment by gigabit101** [comment]
closed due to inactivity
