### ISSUE TITLE
[Bug]: MT Connect not working

### ISSUE THREAD

**Issue by Nandead559** [CreeperHost/CreeperHostGui#747]
### Describe the bug

Cannot open my world

### Steps to reproduce

1. Click Esc button
2. Click open to friends
3. Says attempting to open and either stuck there or says connection was lost

### Expected behaviour

World opens to friends

### Version

6.1.0

### Minecraft Version

1.18.2

### ModLoader Version

Forge

### Additional Information

LOG
[11:20:57] [Render thread/INFO]: [CHAT] Attempting to open world to friends
[11:20:58] [MT Connect Friend Share Executor/INFO]: Selected server lax1. Closest DC was losangeles.
[11:20:58] [MT Connect Friend Share Executor/INFO]: Selected MTConnect server: lax1
[11:21:17] [Netty Server IO #2/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar%2328!/:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[11:21:17] [Netty Server IO #2/INFO]: [CHAT] MineTogether connection lost. Your world is no longer shared to friends.

**Comment by brandon3055** [comment]
We are still experiencing some intermittent issues with the new MT Connect system. 
We hope to have these issues resolved soon.

In the meantime, the problematic nodes should now be working again.
Please check if you are able to connect now.
