### ISSUE TITLE
[Bug]: In-game username change not going through

### ISSUE THREAD

**Issue by Starvalus** [CreeperHost/CreeperHostGui#784]
### Describe the bug

"An error occurred while trying to set name"

### Steps to reproduce

1. Click cog icon by MineTogether chat tab (or in corner of Escape menu)
2. Click "Edit Profile"
3. Click "Change"
4. Select Display Name options of choice
5. Click "Save"
6. "An error occurred while trying to set name"

### Expected behaviour

My display name to be updated 😞 

### Version

Same issue in both 6.2.6 and 6.3.1

### Minecraft Version

1.18.2

### ModLoader Version

Forge 40.2.14

### Additional Information

Let me just say also that I know I can do the name change on the website, however, it seems that the in-game name change system has many words/options to put together that the website name change is lacking, and I'd like to take advantage of those additional options if possible!

**Comment by gigabit101** [comment]
Feel free to reopen the issue when you have a log

**Comment by Starvalus** [comment]
@gigabit101 Ngl I'm new to this site & format and stuff so I'm not sure exactly how to do all that stuff, I did however just put the FTB App console screen on my other monitor and tried the name change again, and the console spit this out when I did

```
[13:39:52] [MT Profile Requests Thread 0/ERROR] [ne.cr.mi.gu.ProfileRequests/]: An error occurred while trying to set name
java.io.IOException: Response for request 'https://minetogether.io/api/v2/name' returned content type 'text/html; charset=utf-8'. I don't know how to handle this yet.
	at net.creeperhost.minetogether.lib.web.ApiClient.execute(ApiClient.java:77) ~[minetogether-forge-1.18.2-6.3.1.jar%23197!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.creeperhost.minetogether.gui.ProfileRequests.lambda$setName$5(ProfileRequests.java:241) ~[minetogether-forge-1.18.2-6.3.1.jar%23197!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Unknown Source) [?:?] {}
```

**Comment by ThePaul-T** [comment]
Can you give it another try now?

**Comment by Starvalus** [comment]
I just tried again, same outcome, and here's the console response

```
[14:40:24] [MT Profile Requests Thread 1/ERROR] [ne.cr.mi.gu.ProfileRequests/]: An error occurred while trying to set name
java.io.IOException: Response for request 'https://minetogether.io/api/v2/name' returned content type 'text/html; charset=utf-8'. I don't know how to handle this yet.
	at net.creeperhost.minetogether.lib.web.ApiClient.execute(ApiClient.java:77) ~[minetogether-forge-1.18.2-6.3.1.jar%23197!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.creeperhost.minetogether.gui.ProfileRequests.lambda$setName$5(ProfileRequests.java:241) ~[minetogether-forge-1.18.2-6.3.1.jar%23197!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Unknown Source) [?:?] {}
```

**Comment by ThePaul-T** [comment]
Are you able to confirm what your selecting as your name? A screenshot would be best.

**Comment by Starvalus** [comment]
I was going for Starfruit and Vex (trying to get as close as I can to my actual username here, was considering checking on other modpacks after the three day cooldown, since it seems that the options available are affected by the mods in the pack?)

Okay I was gonna do it to send screenshots but this time it worked (maybe because I closed and reopened the instance?), or rather, it said it worked but didn't seem to actually update.

![{1A9070BE-BC4C-4056-ACB9-189ABF532E45}](https://github.com/user-attachments/assets/a09f31ae-c112-42c9-8937-7a12569995ad)

(Despite setting off the cooldown timer and displaying it updated in the box, in chat it has not changed)

**Comment by Starvalus** [comment]
Okay after some time it has updated in chat, so seemingly it has gone through.

Was it something on the internal/server side of things? I'm probably too dumb to understand but curious what exactly was causing the issue

**Comment by ThePaul-T** [comment]
I'm not entirely sure yet, as I had not actually done anything that -should- have fixed it, I did make changes though.

**Comment by Starvalus** [comment]
Also as an aside, is there a way to know what mods are adding what words to the possible options? Like I dunno if there's a catalog of potential name options somewhere?
