### ISSUE TITLE
Attempting to delete the "Modpack Partner" entry in server list crashes the game.

### ISSUE THREAD

**Issue by electricman226** [CreeperHost/CreeperHostGui#79]
If you select any server in the list that isn't the "Modpack Partner" entry, and use arrow keys to navigate the to the partner entry, deleting it will crash your game.

Stacktrace:
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.remove(Unknown Source)
    at net.creeperhost.minetogether.gui.serverlist.data.ServerListNoEdit.removeServerData(ServerListNoEdit.java:103)
    at net.minecraft.client.gui.GuiMultiplayer.confirmClicked(GuiMultiplayer.java:196)
    at net.minecraft.client.gui.GuiYesNo.actionPerformed(SourceFile:50)
    at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:443)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by CH-Paul-T** [comment]
Hello,

Can you confirm the version this happened on?

We had an issue like this quite a long time ago, is it possible it's an old version or is this on the latest?

I'll try and recreate the issue myself shortly, just thought it fair we reply asap so you know we are looking into this.

Regards,
Paul
